CREATE TABLE IF NOT EXISTS activity_product (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  description TEXT DEFAULT NULL,
  cover_url VARCHAR(255) DEFAULT NULL,
  total_stock INT NOT NULL,
  available_stock INT NOT NULL,
  price_amount DECIMAL(10, 2) NOT NULL,
  need_payment TINYINT NOT NULL,
  purchase_limit_type VARCHAR(32) NOT NULL,
  purchase_limit_count INT NOT NULL,
  code_source_mode VARCHAR(32) NOT NULL,
  publish_mode VARCHAR(32) NOT NULL,
  publish_status VARCHAR(32) NOT NULL,
  publish_time DATETIME NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS redeem_code (
  id BIGINT NOT NULL AUTO_INCREMENT,
  activity_id BIGINT NOT NULL,
  code VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  batch_no VARCHAR(64) DEFAULT NULL,
  status VARCHAR(32) NOT NULL,
  assigned_user_id BIGINT DEFAULT NULL,
  assigned_order_id BIGINT DEFAULT NULL,
  assigned_at DATETIME DEFAULT NULL,
  invalid_reason VARCHAR(128) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_redeem_code_code (code)
);

CREATE TABLE IF NOT EXISTS order_record (
  id BIGINT NOT NULL AUTO_INCREMENT,
  order_no VARCHAR(64) NOT NULL,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  purchase_unique_key VARCHAR(128) NOT NULL,
  order_status VARCHAR(32) NOT NULL,
  pay_status VARCHAR(32) NOT NULL,
  code_status VARCHAR(32) NOT NULL,
  price_amount DECIMAL(10, 2) NOT NULL,
  fail_reason VARCHAR(128) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_order_no (order_no),
  UNIQUE KEY uk_order_purchase_unique_key (purchase_unique_key)
);

CREATE TABLE IF NOT EXISTS export_task (
  id BIGINT NOT NULL AUTO_INCREMENT,
  activity_id BIGINT NOT NULL,
  operator_id BIGINT NOT NULL,
  format VARCHAR(16) NOT NULL,
  filters_json VARCHAR(2000) DEFAULT NULL,
  status VARCHAR(32) NOT NULL,
  file_url VARCHAR(255) DEFAULT NULL,
  fail_reason VARCHAR(128) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  biz_type VARCHAR(32) NOT NULL,
  biz_key VARCHAR(128) NOT NULL,
  operation VARCHAR(64) NOT NULL,
  operator_id BIGINT DEFAULT NULL,
  request_id VARCHAR(64) DEFAULT NULL,
  detail_json VARCHAR(4000) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compensation_record (
  id BIGINT NOT NULL AUTO_INCREMENT,
  biz_type VARCHAR(32) NOT NULL,
  biz_key VARCHAR(128) NOT NULL,
  source_event VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  reason VARCHAR(128) NOT NULL,
  payload_json VARCHAR(4000) DEFAULT NULL,
  resolution_note VARCHAR(255) DEFAULT NULL,
  resolved_at DATETIME DEFAULT NULL,
  resolved_by BIGINT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
