CREATE TABLE IF NOT EXISTS activity_product (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  description TEXT DEFAULT NULL,
  cover_url VARCHAR(255) DEFAULT NULL,
  total_stock INT NOT NULL,
  available_stock INT NOT NULL,
  price_amount DECIMAL(10, 2) NOT NULL,
  need_payment TINYINT NOT NULL,
  purchase_limit_type VARCHAR(32) NOT NULL,
  purchase_limit_count INT NOT NULL,
  code_source_mode VARCHAR(32) NOT NULL,
  publish_mode VARCHAR(32) NOT NULL,
  publish_status VARCHAR(32) NOT NULL,
  publish_time DATETIME NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS redeem_code (
  id BIGINT NOT NULL AUTO_INCREMENT,
  activity_id BIGINT NOT NULL,
  code VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  batch_no VARCHAR(64) DEFAULT NULL,
  status VARCHAR(32) NOT NULL,
  assigned_user_id BIGINT DEFAULT NULL,
  assigned_order_id BIGINT DEFAULT NULL,
  assigned_at DATETIME DEFAULT NULL,
  invalid_reason VARCHAR(128) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS redeem_code_import_batch (
  id BIGINT NOT NULL AUTO_INCREMENT,
  activity_id BIGINT NOT NULL,
  batch_no VARCHAR(64) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  total_count INT NOT NULL,
  success_count INT NOT NULL,
  failed_count INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS redeem_code_import_fail_detail (
  id BIGINT NOT NULL AUTO_INCREMENT,
  activity_id BIGINT NOT NULL,
  batch_no VARCHAR(64) NOT NULL,
  line_no INT NOT NULL,
  raw_code VARCHAR(128) DEFAULT NULL,
  failure_reason VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
