CREATE TABLE IF NOT EXISTS activity_product (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  description TEXT DEFAULT NULL,
  cover_url VARCHAR(255) DEFAULT NULL,
  total_stock INT NOT NULL,
  available_stock INT NOT NULL,
  price_amount DECIMAL(10, 2) NOT NULL,
  need_payment TINYINT NOT NULL,
  purchase_limit_type VARCHAR(32) NOT NULL,
  purchase_limit_count INT NOT NULL,
  code_source_mode VARCHAR(32) NOT NULL,
  publish_mode VARCHAR(32) NOT NULL,
  publish_status VARCHAR(32) NOT NULL,
  publish_time DATETIME NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS order_record (
  id BIGINT NOT NULL AUTO_INCREMENT,
  order_no VARCHAR(64) NOT NULL,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  purchase_unique_key VARCHAR(128) NOT NULL,
  order_status VARCHAR(32) NOT NULL,
  pay_status VARCHAR(32) NOT NULL,
  code_status VARCHAR(32) NOT NULL,
  price_amount DECIMAL(10, 2) NOT NULL,
  fail_reason VARCHAR(128) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_order_no (order_no),
  UNIQUE KEY uk_order_purchase_unique_key (purchase_unique_key)
);

CREATE TABLE IF NOT EXISTS payment_record (
  id BIGINT NOT NULL AUTO_INCREMENT,
  order_no VARCHAR(64) NOT NULL,
  transaction_no VARCHAR(64) NOT NULL,
  pay_amount DECIMAL(10, 2) NOT NULL,
  pay_status VARCHAR(32) NOT NULL,
  callback_payload VARCHAR(2000) DEFAULT NULL,
  paid_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_transaction_no (transaction_no)
);
